# Uncomment the next line to define a global platform for your project
# platform :ios, '14.0'

target 'REDOIT-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'Kingfisher'
	pod 'Moya'
	pod 'Moya/Combine'
	pod 'Alamofire'

  # Pods for REDOIT-iOS

end